# Spring Boot configuration
spring:
  application:
    name: elastic demo
# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo?createDatabaseIfNotExist=true
    username: demo
    password: demo
# JPA properties
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format-sql: true
        jdbc:
          lob:
            non-contextual-creation: true
    hibernate:
      ddl-auto: update

# Logger configuration
  logging:
    level:
      org.springframewok: INFO
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: app.log
# Server configuration
server:
  port: 8080
  sessionTimeout: 30
test:
  data:
    entityCount: 1000000
    rangeDate: 50
    resPathNameDictionary: dictionary.txt
elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  indexName: element
  resPathSetting: "elasticsearch/settings.json"
  resPathMapping: "elasticsearch/mapping.json"
  fetchLimit: 5000